### ISSUE TITLE
BMS 컨테이너 내부에서 CUDA device를 찾지 못하는 경우

### ISSUE THREAD

**Issue by ML-TANGO** [ML-TANGO/TANGO#126]
BMS에서 가끔 CUDA Device를 찾을 수 없다고 나오는 경우, docker-compose down후 다음 명령 실행하면 해결.
```bash
sudo docker run --rm --runtime=nvidia --gpus all nvidia/cuda:11.8.0-base-ubuntu20.04 nvidia-smi
```
* 해당 문제는 발생 원인은 알수 없음.
*  출처: https://velog.io/@cjw9105/NVIDIA-Container-Toolkit-%EC%84%A4%EC%B9%98

**Comment by ML-TANGO** [comment]
신익수연구원이 제공한 내용

**Comment by iksooman** [comment]
관련 내용을 검색해봤는데 [여기](https://github.com/NVIDIA/nvidia-docker/issues/1730#issue-1573551271:~:text=Set%20the%20parameter%20%22exec%2Dopts%22%3A%20%5B%22native.cgroupdriver%3Dcgroupfs%22%5D%20in%20the%20/etc/docker/daemon.json%20file)에서 언급하고 있는 것과 동일한 현상일 것 같습니다.
