### ISSUE TITLE
code_gen container 빌드 시 에러

### ISSUE THREAD

**Issue by sejeong98105** [ML-TANGO/TANGO#129]
code_gen container를 빌드하는 과정에서 아래와 같은 오류가 발생합니다.

<img width="1650" alt="스크린샷 2023-12-05 오후 2 43 04" src="https://github.com/ML-TANGO/TANGO/assets/51065191/00936519-3086-490c-b996-39be1d545e1d">

**Comment by sejeong98105** [comment]
code gen 실행 시 아래와 같은 결과가 나옵니다. 

```
yoloe- status_request response : completed
2023-12-07T08:20:25.102992466Z _________GET /status_request_____________
2023-12-07T08:20:25.108835110Z tracked yoloe process you want, but not running anymore
2023-12-07T08:20:25.108877760Z nasinfo.status: completed
2023-12-07T08:20:25.110674174Z [07/Dec/2023 08:20:25] "GET /status_request?user_id=user01&project_id=3 HTTP/1.1" 200 11
Auto NN 완료
```

**Comment by iksooman** [comment]
아래 commit 내용을 좀더 설명해드리면,
https://github.com/ML-TANGO/TANGO/pull/130

code_gen에서 cmake를 3.20 버전 이상으로 고정시킨 것이 주요 변경 사항입니다.
처음에 이슈화시켜주신 내용을 확인해보니 cmake 버전 3.20 이하에서 해당 에러가 발생했습니다.
따라서 최신 코드를 pull하신 뒤에 code_gen 이미지를 새로 빌드하시면 cmake 버전 3.22.1로 변경되어 실행될 것입니다.

**Comment by sejeong98105** [comment]
네 위의 내용이 새로 빌드하여 code gen 실행시킨 결과입니다.

**Comment by iksooman** [comment]
아래 명령어로 code_gen에 접속하신 뒤에
```
docker exec -it tango_code_gen_1 /bin/bash
```
아래 명령어로
```
cmake --version
```
버전 정보 캡쳐 부탁드립니다.

**Comment by sejeong98105** [comment]
빌드하는 과정에서 제대로 안됐던 거 같습니다. 

해결되었습니다. 감사합니다.
