### ISSUE TITLE
project_manager never call /start api for viz2code 

### ISSUE THREAD

**Issue by HyunwooCho** [ML-TANGO/TANGO#146]
It is 'Visualization' tab, left sidebar in the main page (port:8085).
I expect that **Project Manager would call GET /start REST API to viz2code if I clicked the tab.**
However, it did not. Actually it can not do it because I did not create a project, which means Project Manager did not have a project tocken({user_id}/{project_id}) and then it can not call GET /start with {user_id} and {project_id}.
I think Project Manager just call "GET /" to show viz2code's templete view.
Problem is that viz2code is supposed to save their status based on key combination {user_id} and {project_id}. In other words, viz2code can not save any status information.
So viz2code never store their running status in its Django Model list so it can not report back to Project Manager when it finishes its task.

I think we have two options to solve it.

- First, Project Manager blocks to click 'Visualization' tab until an user creates a 'Project'. This option has aleady applied to BMS and AutoNN.

- Second, Project Manager can call viz2code without {user_id} and {project_id} and viz2code also modifies its REST API GET /start, /stop, /status_request, /status_report to create, retreive, update and delete without {user_id} and {project_id}. Only Project manager links to one of its works of viz2code with a certain 'Project. This option has already applied to Dataset and Target.

> - (one small trick to work around) This is a variation of second option. Project Manager creates temporary {user_id}/{project_id} and call GET /start API for viz2code when users click the 'Visualization' tab. After that, if they set a real project, Project Manager show the model selection step, like dataset and target selection steps. Project Manager "manages" the temporary tocken in its database to link the generated neural network model with the real project. 

We need to decide which is better.
In my opinion, first option is secure and clear, but too limited to re-use a neural network model. We should make the same model for different project, even for the same user. I think second one is more flexible and easy to use for users, but we need to re-define REST APIs and Project Manager should treat with more complex database and linkage.

**Comment by ML-TANGO** [comment]
화면 좌측의 Visualization 버튼은 프로젝트 초기에 시각화 시연을 위하여 만든 것으로 최종적으로 제거되어야 합니다.
- TANGO 초기 시연시, 프로젝트 설정과는 무관하게 시각화 기능을 단독으로 보여주기 위하여 사용하였음.

**Comment by HyunwooCho** [comment]
좌측 Visualization 버튼을 없앤다면 
- 언제 Project Manager는 viz2code로 GET /start API를 호출할까요? (현재는 어떠한 경우에도 호출하지 않음)
- Project Manager에서 프로젝트 생성을 하면 viz2code에 접근할 방법이 없어집니다. 따라서 버튼을 하나 만들어야 합니다.

만약 BMS와 AutoNN 사이에 Visualization이 들어가도록 만든다면
- GET /start API가 {user_id}/{project_id} 기반으로 호출되는데 너무 불편합니다. 왜냐하면 데이터셋이나 타겟만 바뀐 프로젝트를 몇 개 더 만들고 동일한 신경망으로 비교 시험을 하고 싶으면 다시 처음부터 신경망을 만들어야 합니다.
- 왜냐하면 신경망 결과를 저장하는 디렉토리가 shared/common/{user_id}/{project_id}/ 아래이기 때문입니다. 다른 프로젝트에서 여기에 접근할 수가 없습니다.     

따라서 제 제안은 다음과 같습니다. 
- Visualization은 별도의 버튼으로 나눕니다. 지금처럼

> - 대신에 Visualization과 Project Manager 사이에는 별도의 REST API를 정의하여 사용합니다. POST /new_nn 정도?
> - Visualization에서 만든 결과는 {user_id}/{project_id}/ 아래에 저장하는 것이 아니라 별도의 디렉토리에 저장합니다.
> - Project Manager는 사용자가 쉽게 기존에 만들어진 신경망으로 선택할 수 있도록 리스트를 보여 줍니다. 마치 target이나 dataset에서 그렇게 하고 있는 것처럼
> - 만들어진 신경망 중 하나를 선택하는 것은 BMS의 front-end로 처리하거나 Project Manger에서 보여주어도 됩니다.

 
-  일단 프로젝트가 만들어지고 신경망까지 선택된 후에는

> - BMS와 AutoNN 사이에 다시 Visualization이 들어갑니다. 왜냐하면 약간 수정하기 원할 수도 있으므로
> - 여기서 수정된 신경망 역시 {user_id}/{project_id}와는 상관없이 저장합니다. 왜냐하면 다른 프로젝트에서 가져다 쓰기 쉽게 하기 위해
> - 물론 그것에 대한 데이터베이스 관리는 Project Manager가 담당합니다. 이를 위해 다시 위에서 정한 REST API로 POST 합니다.
