### ISSUE TITLE
도커 빌드를 수행할 때마다 디스크 용량을 더 많이 차지하는 현상

### ISSUE THREAD

**Issue by HyunwooCho** [ML-TANGO/TANGO#147]
테스트 & 수정을 위해 
1. 하나의 도커 컨테이너에 대해 소스 코드를 자주 변경, 저장
2. 도커 컨테이너 삭제 및 이미지 삭제를 한 후,
3. 도커 재빌드
4. 도커 컨테이너 up

이 과정을 반복함에 따라 점차 파일 시스템 용량이 증가하면서 결국 디스크 용량이 부족해지고 있음
약 300G까지 늘어나서 결국 용량 부족 경고가 뜸

(임시방편으로) 
docker system prune
docker volume rm $(docker volume ls)
와 같은 방법으로 초기화 후 전체 도커 컨테이너 재빌드

도커 이미지까지 지우는데 어디에 자꾸 쓰레기가 쌓이는지 모르겠음
도커 전체를 다 cleanup 하는 방식 이외의 방법이 있는지 알고 싶음

**Comment by ML-TANGO** [comment]
도커에서는 사용하지 않는 대상 오브젝트들을 보수적인 방법 (명시적으로 명령을 통하여 삭제)으로 관리하므로, 위에서 사용하신 명령들을 통하여 명시적으로 삭제해주야 합니다. TANGO의 경우 보통 다음과 같이 사용합니다.
* volume은 데이타셋등이 포함되어 재구축에 시간이 많이 소요되므로 일반적으로 삭제하지 않고 재사용
* 이미지만을 주로 정리하며, `docker image prune -a` 명령을 통하여 컨테이너에서 사용하지 않는 모든 이미지 정리

**Comment by ML-TANGO** [comment]
From

First to find out what is using the space:
```docker system df``` [see docs](https://docs.docker.com/engine/reference/commandline/system_df/)

In my case most of it was used by "Build cache", to remove it:
```docker builder prune``` [see docs](https://docs.docker.com/engine/reference/commandline/builder_prune/)


source: https://stackoverflow.com/a/77372285/4773896

**Comment by HyunwooCho** [comment]
저의 경우 개발 중 가장 많은 용량이 지속적으로 쌓이는 것은 build cache인 것으로 확인되었습니다.
따라서 docker builder prune 명령어가 적당한 방법이었습니다.

cf) docker system prune은 정지된 docker container/image까지 모두 지우기 때문에 주의 필요
