### ISSUE TITLE
Unified AutoNN

### ISSUE THREAD

**Issue by ML-TANGO** [ML-TANGO/TANGO#157]
# Unified AutoNN Container (2024)

* source location: `autonn/autonn`
   * combine BMS + Visualizer +AutoNN (YoloE/ResNet) + NAS + HPO functionality
   * container port number: 8100  (PM should call start api with 8100 port)

> no need for `basemodel.yaml` used between old BMS and AutoNN

* Result: Simplified Pipeline 
   * AutoNN => Code Gen => Target Deploy

Schedule:
* 2024.06.15 : Unified AutoNN template supports start() API
* 2024.07.15:  combine BMS + Visualizer functionality + YoloE (ETRI YoloV9)
* 2024.08.15:  combine other functionality

**Comment by ML-TANGO** [comment]
Unified AutoNN Container 구현은 TANGO 또는 TANGO-SDV (CI CD용 저장소를 분리하는 경우) 공통적으로 적용되는 기능인가?

**Comment by HyunwooCho** [comment]
통합 AutoNN 완료
