### ISSUE TITLE
Caching Dataset thumbnail image

### ISSUE THREAD

**Issue by ML-TANGO** [ML-TANGO/TANGO#160]
프로젝트 설정시 데이타셋 선택하는 부분에서 표시되는 데이타셋 thumbnail 이미지에 대하여 
- thumbnail 이미지 생성시 한번 생성되었으면 캐슁하여 매번 생성하지 않도록 수정요망
- thumbnail 이미지 우측의 파일 갯수와 크기 정보

**Comment by HyunwooCho** [comment]
test
