### ISSUE TITLE
Model Viz / Log Viz 더블 탭 구현 요청

### ISSUE THREAD

**Issue by HyunwooCho** [ML-TANGO/TANGO#189]
Train 도중에도 Model을 확인할 수 있도록 더블 탭으로 구성 요청

![image](https://github.com/user-attachments/assets/ed272ffc-9de1-4753-b81b-27be80a4f3ae)

**Comment by ML-TANGO** [comment]
https://github.com/ML-TANGO/TANGO/pull/194
